name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@master
        with:
          github_user_name: suellenferraz
          output_path: "./output/github-contribution-grid-snake.svg"  # Caminho para gerar o arquivo

      - name: Commit & Push the generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: add snake contribution graph"
          add: "./output/github-contribution-grid-snake.svg"  # Garante que o arquivo será adicionado
