name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # executa todos os dias à meia-noite
  workflow_dispatch:      # permite rodar manualmente pelo GitHub

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@master
        with:
          github_user_name: suellenferraz
          output_path: output/github-contribution-grid-snake.svg

      - name: Commit & Push SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: generate contribution graph with snake"
          add: "output/github-contribution-grid-snake.svg"
